### ISSUE TITLE
\n Compatibility 

### ISSUE THREAD

**Issue by BlueKill456** [HakanBabus/EasyAnnouncement#1]
Hello, as a suggestion you should add \n to make a space after each text, right now if you use "\n" it does not make the line space below

**Comment by bobbyshmurdaa99** [comment]
You can use AutoAnnouncer, much better plugin, it allows you to have multiple rows of messages per announcement.

**Comment by HakanBabus** [comment]
> You can use AutoAnnouncer, much better plugin, it allows you to have multiple rows of messages per announcement.

?
